### ISSUE TITLE
Received 16 bytes on script command interface. Expecting 4 bytes, so ignoring this message

### ISSUE THREAD

**Issue by Aruen24** [catmulti7/dual_ur_ros_2#3] opened 2024-10-30 07:46 UTC
ur_ros2_control_node-1] [ERROR] [1730274040.818279203] [arm_0.controller_manager]: Could not switch controllers since prepare command mode switch was rejected.
[spawner-7] [INFO] [1730274040.818849927] [arm_0.spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[spawner-8] [ERROR] [1730274040.819171291] [arm_0.spawner_io_and_status_controller]: Failed to activate controller
[INFO] [spawner-22]: process has finished cleanly [pid 75423]
[INFO] [spawner-20]: process has finished cleanly [pid 75419]
[INFO] [spawner-18]: process has finished cleanly [pid 75415]
[spawner-10] [INFO] [1730274040.838564576] [arm_0.spawner_force_torque_sensor_broadcaster]: Configured and activated force_torque_sensor_broadcaster
[ur_ros2_control_node-1] [INFO] [1730274040.839740480] [arm_0.controller_manager]: Loading controller 'scaled_joint_trajectory_controller'
[ur_ros2_control_node-1] [WARN] [1730274040.850590888] [arm_0.scaled_joint_trajectory_controller]: [Deprecated]: "allow_nonzero_velocity_at_trajectory_end" is set to true. The default behavior will change to false.
[spawner-6] [INFO] [1730274040.858434263] [arm_0.spawner_scaled_joint_trajectory_controller]: Loaded scaled_joint_trajectory_controller
[ur_ros2_control_node-1] [INFO] [1730274040.859132704] [arm_0.controller_manager]: Configuring controller 'scaled_joint_trajectory_controller'
[ur_ros2_control_node-1] [INFO] [1730274040.859325952] [arm_0.scaled_joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ur_ros2_control_node-1] [INFO] [1730274040.859351259] [arm_0.scaled_joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ur_ros2_control_node-1] [INFO] [1730274040.859467540] [arm_0.scaled_joint_trajectory_controller]: Using 'splines' interpolation method.
[ur_ros2_control_node-1] [INFO] [1730274040.859862837] [arm_0.scaled_joint_trajectory_controller]: Controller state will be published at 100.00 Hz.
[ur_ros2_control_node-1] [INFO] [1730274040.861476292] [arm_0.scaled_joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[spawner-6] [INFO] [1730274040.888295867] [arm_0.spawner_scaled_joint_trajectory_controller]: Configured and activated scaled_joint_trajectory_controller
[INFO] [spawner-11]: process has finished cleanly [pid 75401]
[INFO] [spawner-9]: process has finished cleanly [pid 75397]
[ERROR] [spawner-8]: process has died [pid 75395, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner io_and_status_controller --controller-manager controller_manager --controller-manager-timeout 10 --ros-args -r __ns:=/arm_0'].
[INFO] [spawner-7]: process has finished cleanly [pid 75393]
[INFO] [spawner-10]: process has finished cleanly [pid 75399]
[INFO] [spawner-6]: process has finished cleanly [pid 75391]
[ur_ros2_control_node-12] [WARN] [1730274047.765991811] [UR_Client_Library:arm_1_]: Received 16 bytes on script command interface. Expecting 4 bytes, so ignoring this message
[ur_ros2_control_node-1] [WARN] [1730274051.580702023] [UR_Client_Library:arm_0_]: Received 16 bytes on script command interface. Expecting 4 bytes, so ignoring this message

**Comment by catmulti7** [comment] 2024-10-30 08:04
Hi @Aruen24,
I think this problem is caused by a mismatched version of the `ur_robot_driver` in this repo and the `UR_Client_Library` you installed. I haven't tried it, but I believe replacing the `ur_robot_driver` folder in this repo with the same folder from the [official repo](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver) might fix the issue.
PS. I've made some changes to `ur_robot_driver`. I think I added `arm_0_ur_controllers.yaml`, `arm_1_ur_controllers.yaml`, and `dual_ur_control.launch.py`, and modified `ur_control.launch.py`. So, remember to keep these files unchanged.

**Comment by Aruen24** [comment] 2024-10-31 01:02
> Hi @Aruen24, I think this problem is caused by a mismatched version of the `ur_robot_driver` in this repo and the `UR_Client_Library` you installed. I haven't tried it, but I believe replacing the `ur_robot_driver` folder in this repo with the same folder from the [official repo](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver) might fix the issue. PS. I've made some changes to `ur_robot_driver`. I think I added `arm_0_ur_controllers.yaml`, `arm_1_ur_controllers.yaml`, and `dual_ur_control.launch.py`, and modified `ur_control.launch.py`. So, remember to keep these files unchanged.

@catmulti7  I install UR_Client_Library by apt-get install ros-humble-ur-client-library.
Also replacing the ur_robot_driver folder in this repo with the same folder from the [official repo](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver)  but get the same error.

**Comment by catmulti7** [comment] 2024-10-31 03:45
@Aruen24,
You deleted your previous comment, has your problem been resolved?
I can reproduce your issue when I set `headless_mode` in `ur_control.launch.py` to `false`, when I set this param to `true` is seems to work well.

**Comment by catmulti7** [comment] 2024-10-31 03:47
@Aruen24,
You deleted your previous comment, has your problem been resolved?
I can reproduce your issue when I set `headless_mode` in `ur_control.launch.py` to `false`, when I set this param to `true` is seems to work well.

**Comment by Aruen24** [comment] 2024-10-31 03:53
> @Aruen24, You deleted your previous comment, has your problem been resolved? I can reproduce your issue when I set `headless_mode` in `ur_control.launch.py` to `false`, when I set this param to `true` is seems to work well

@catmulti7 I have solved the problem.

**Comment by catmulti7** [comment] 2024-10-31 03:57
@Aruen24
I will close this issue since it has been solved. Feel free to reopen it or create another issue if you have any other problem.

**Closed as completed by catmulti7** 2024-10-31 03:57 UTC
